on: push

env:
  JENKINS_HOST: https://jenkins-gldtn-tv2-sdk.cmo.conti.de
  JENKINS_JOB: job/testjob
  JENKINS_USER: uif91573
  JENKINS_TOKEN: 11644fa659f5d2497d502097e4f8becd19

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      -
        name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@master
        with:
          JENKINS_HOST: ${{ env.JENKINS_HOST }}
          JENKINS_JOB: ${{ env.JENKINS_JOB }}
          JENKINS_TOKEN: 11644fa659f5d2497d502097e4f8becd19
          JENKINS_USER: uif91573
