on: push

env:
  JENKINS_HOST: https://jenkins-gldtn-tv2-sdk.cmo.conti.de/
  JENKINS_JOB: job/pipetest
  JENKINS_USER: uig45131
  JENKINS_TOKEN: 11d159eda41f6ec09a9b29a66aa44b9d7e

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      -
        name: Trigger Jenkins Job
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_user: ${{ env.JENKINS_USER }}
          jenkins_token: ${{ env.JENKINS_TOKEN }}
          jenkins_url: ${{ env.JENKINS_HOST }}
          job_name: "pipetest"
